FROM rust:1.41 AS builder
RUN rustup override set nightly

WORKDIR /usr/src/hello-rocket
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update \
&& apt-get upgrade -y \
&& rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/cargo/bin/hello-rocket /usr/local/bin/hello-rocket
CMD ["hello-rocket"]
