FROM rust:1.41 AS builder
RUN rustup override set nightly

WORKDIR /usr/src/hello-rocket
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
COPY --from=builder /usr/local/cargo/bin/hello-rocket /usr/local/bin/hello-rocket
CMD ["hello-rocket"]
